/*
 * generated by Xtext 2.12.0
 */
package org.slizaa.neo4j.opencypher


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
class OpenCypherRuntimeModule extends AbstractOpenCypherRuntimeModule {
}
