/**
 * generated by Xtext 2.13.0
 */
package org.slizaa.neo4j.opencypher.openCypher;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>All Shortest Paths</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see org.slizaa.neo4j.opencypher.openCypher.OpenCypherPackage#getAllShortestPaths()
 * @model
 * @generated
 */
public interface AllShortestPaths extends ShortestPathPattern
{
} // AllShortestPaths
