/**
 * generated by Xtext 2.13.0
 */
package org.slizaa.neo4j.opencypher.openCypher;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Combined Query</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.slizaa.neo4j.opencypher.openCypher.CombinedQuery#getSingleQuery <em>Single Query</em>}</li>
 *   <li>{@link org.slizaa.neo4j.opencypher.openCypher.CombinedQuery#getUnion <em>Union</em>}</li>
 * </ul>
 *
 * @see org.slizaa.neo4j.opencypher.openCypher.OpenCypherPackage#getCombinedQuery()
 * @model
 * @generated
 */
public interface CombinedQuery extends RegularQuery
{
  /**
   * Returns the value of the '<em><b>Single Query</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Single Query</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Single Query</em>' containment reference.
   * @see #setSingleQuery(SingleQuery)
   * @see org.slizaa.neo4j.opencypher.openCypher.OpenCypherPackage#getCombinedQuery_SingleQuery()
   * @model containment="true"
   * @generated
   */
  SingleQuery getSingleQuery();

  /**
   * Sets the value of the '{@link org.slizaa.neo4j.opencypher.openCypher.CombinedQuery#getSingleQuery <em>Single Query</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Single Query</em>' containment reference.
   * @see #getSingleQuery()
   * @generated
   */
  void setSingleQuery(SingleQuery value);

  /**
   * Returns the value of the '<em><b>Union</b></em>' containment reference list.
   * The list contents are of type {@link org.slizaa.neo4j.opencypher.openCypher.Union}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Union</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Union</em>' containment reference list.
   * @see org.slizaa.neo4j.opencypher.openCypher.OpenCypherPackage#getCombinedQuery_Union()
   * @model containment="true"
   * @generated
   */
  EList<Union> getUnion();

} // CombinedQuery
