/**
 * generated by Xtext 2.13.0
 */
package org.slizaa.neo4j.opencypher.openCypher;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Expression</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see org.slizaa.neo4j.opencypher.openCypher.OpenCypherPackage#getExpression()
 * @model
 * @generated
 */
public interface Expression extends EObject
{
} // Expression
