/**
 * generated by Xtext 2.13.0
 */
package org.slizaa.neo4j.opencypher.openCypher;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Implicit Procedure Invocation</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see org.slizaa.neo4j.opencypher.openCypher.OpenCypherPackage#getImplicitProcedureInvocation()
 * @model
 * @generated
 */
public interface ImplicitProcedureInvocation extends EObject
{
} // ImplicitProcedureInvocation
