/*
 * generated by Xtext 2.13.0
 */
package org.slizaa.neo4j.opencypher.web;

import org.eclipse.xtext.web.server.DefaultWebModule;

/**
 * Manual modifications go to {@link OpenCypherWebModule}.
 */
@SuppressWarnings("all")
public abstract class AbstractOpenCypherWebModule extends DefaultWebModule {

}
