/**
 * generated by Xtext 2.13.0
 */
package org.slizaa.neo4j.opencypher.openCypher.impl;

import org.eclipse.emf.ecore.EClass;

import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.slizaa.neo4j.opencypher.openCypher.OpenCypherPackage;
import org.slizaa.neo4j.opencypher.openCypher.RemoveItem;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Remove Item</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class RemoveItemImpl extends MinimalEObjectImpl.Container implements RemoveItem
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected RemoveItemImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return OpenCypherPackage.Literals.REMOVE_ITEM;
  }

} //RemoveItemImpl
