/**
 * generated by Xtext 2.13.0
 */
package org.slizaa.neo4j.opencypher.openCypher.impl;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;

import org.slizaa.neo4j.opencypher.openCypher.OpenCypherPackage;
import org.slizaa.neo4j.opencypher.openCypher.PatternElement;
import org.slizaa.neo4j.opencypher.openCypher.ShortestPathPattern;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Shortest Path Pattern</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link org.slizaa.neo4j.opencypher.openCypher.impl.ShortestPathPatternImpl#getPatternElement <em>Pattern Element</em>}</li>
 * </ul>
 *
 * @generated
 */
public class ShortestPathPatternImpl extends AnonymousPatternPartImpl implements ShortestPathPattern
{
  /**
   * The cached value of the '{@link #getPatternElement() <em>Pattern Element</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getPatternElement()
   * @generated
   * @ordered
   */
  protected PatternElement patternElement;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected ShortestPathPatternImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return OpenCypherPackage.Literals.SHORTEST_PATH_PATTERN;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public PatternElement getPatternElement()
  {
    return patternElement;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetPatternElement(PatternElement newPatternElement, NotificationChain msgs)
  {
    PatternElement oldPatternElement = patternElement;
    patternElement = newPatternElement;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, OpenCypherPackage.SHORTEST_PATH_PATTERN__PATTERN_ELEMENT, oldPatternElement, newPatternElement);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setPatternElement(PatternElement newPatternElement)
  {
    if (newPatternElement != patternElement)
    {
      NotificationChain msgs = null;
      if (patternElement != null)
        msgs = ((InternalEObject)patternElement).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - OpenCypherPackage.SHORTEST_PATH_PATTERN__PATTERN_ELEMENT, null, msgs);
      if (newPatternElement != null)
        msgs = ((InternalEObject)newPatternElement).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - OpenCypherPackage.SHORTEST_PATH_PATTERN__PATTERN_ELEMENT, null, msgs);
      msgs = basicSetPatternElement(newPatternElement, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, OpenCypherPackage.SHORTEST_PATH_PATTERN__PATTERN_ELEMENT, newPatternElement, newPatternElement));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case OpenCypherPackage.SHORTEST_PATH_PATTERN__PATTERN_ELEMENT:
        return basicSetPatternElement(null, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case OpenCypherPackage.SHORTEST_PATH_PATTERN__PATTERN_ELEMENT:
        return getPatternElement();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case OpenCypherPackage.SHORTEST_PATH_PATTERN__PATTERN_ELEMENT:
        setPatternElement((PatternElement)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case OpenCypherPackage.SHORTEST_PATH_PATTERN__PATTERN_ELEMENT:
        setPatternElement((PatternElement)null);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case OpenCypherPackage.SHORTEST_PATH_PATTERN__PATTERN_ELEMENT:
        return patternElement != null;
    }
    return super.eIsSet(featureID);
  }

} //ShortestPathPatternImpl
