/*
 * generated by Xtext 2.12.0
 */
package org.slizaa.neo4j.opencypher.web


/**
 * Use this class to register additional components to be used within the web application.
 */
class OpenCypherWebModule extends AbstractOpenCypherWebModule {
}
